#ifndef COBFS4_CONSTANTS
#define COBFS4_CONSTANTS

#define COBFS4_SECRET_KEY_LEN 32
#define COBFS4_TAG_LEN 16
#define COBFS4_IV_LEN 12
#define COBFS4_BLOCK_LEN 16 //Only used for deterministic RNG

#define COBFS4_PUBKEY_LEN 32
#define COBFS4_PRIVKEY_LEN 32
#define COBFS4_ELLIGATOR_LEN 32

#define COBFS4_HMAC_LEN 32
#define COBFS4_HASH_LEN 32

#define COBFS4_AUTH_LEN 32
#define COBFS4_SEED_LEN 32

#define COBFS4_SIPHASH_KEY_LEN 16
#define COBFS4_SIPHASH_IV_LEN 8

//Oh no, this will make my code break on January 29 2084
#define COBFS4_EPOCH_HOUR_LEN 6

#define COBFS4_MAX_HANDSHAKE_SIZE 8192

#define COBFS4_SERVER_HANDSHAKE_LEN (COBFS4_ELLIGATOR_LEN + COBFS4_AUTH_LEN + COBFS4_HMAC_LEN + COBFS4_EPOCH_HOUR_LEN + COBFS4_HMAC_LEN + COBFS4_INLINE_SEED_FRAME_LEN)
#define COBFS4_SERVER_MIN_PAD_LEN (0)
#define COBFS4_SERVER_MAX_PAD_LEN (COBFS4_MAX_HANDSHAKE_SIZE - COBFS4_SERVER_HANDSHAKE_LEN)

#define COBFS4_SERVER_TIMING_SEED_LEN (32)

#define COBFS4_CLIENT_HANDSHAKE_LEN (COBFS4_ELLIGATOR_LEN + COBFS4_HMAC_LEN + COBFS4_EPOCH_HOUR_LEN + COBFS4_HMAC_LEN)
#define COBFS4_CLIENT_MIN_PAD_LEN (COBFS4_SERVER_HANDSHAKE_LEN - COBFS4_CLIENT_HANDSHAKE_LEN)
#define COBFS4_CLIENT_MAX_PAD_LEN (COBFS4_MAX_HANDSHAKE_SIZE - COBFS4_CLIENT_HANDSHAKE_LEN)

#define COBFS4_MAX_FRAME_LEN (1448)
#define COBFS4_FRAME_LEN (2)
#define COBFS4_FRAME_PAYLOAD_OVERHEAD (COBFS4_TAG_LEN + 3)
#define COBFS4_FRAME_OVERHEAD (COBFS4_FRAME_PAYLOAD_OVERHEAD + COBFS4_FRAME_LEN)
#define COBFS4_MAX_FRAME_PAYLOAD_LEN (COBFS4_MAX_FRAME_LEN - COBFS4_FRAME_LEN)
#define COBFS4_MAX_DATA_LEN (COBFS4_MAX_FRAME_PAYLOAD_LEN - COBFS4_FRAME_PAYLOAD_OVERHEAD)

#define COBFS4_INLINE_SEED_FRAME_LEN (COBFS4_SERVER_TIMING_SEED_LEN + COBFS4_FRAME_PAYLOAD_OVERHEAD)

enum frame_type {
    TYPE_PAYLOAD = 0,
    TYPE_PRNG_SEED,
};

#endif
